version: "27.3.1"

services:
  npm:
    image: node:latest
    working_dir: /app
    entrypoint: ["npm"]
    volumes: 
      - .:/app
  node:
    build:
      context: .
      dockerfile: dockerfiles/node-ts.dockerfile
    working_dir: /app
    entrypoint: ["ts-node"]
    volumes: 
      - .:/app
